---
  - name: Update Local DNS on Piholes
    register: dns_update
    copy:
      src: "{{ rpi_src_path }}"
      dest: "{{ rpi_dst_path }}"
      owner: "{{ rpi_file_owner }}"
      group: "{{ rpi_file_group }}"
      mode: "{{ rpi_file_mode }}"

  - name: Restart Local DNS on Piholes
    shell: "{{ rpi_restart_cmd }}"
    when: dns_update.changed == true

