---
- name: Start Nodes
  command: /usr/sbin/qm start "{{ item }}"
  loop:
    - 102
    - 106
    - 107
    - 108
    - 110
    - 111
    - 112
    - 113
  tags:
    - start

- name: Stop Nodes
  command: /usr/sbin/qm stop "{{ item }}"
  loop:
    - 102
    - 106
    - 107
    - 108
    - 110
    - 111
    - 112
    - 113
  tags:
   - stop

- name: Reset Nodes to Base Snapshot
  command: /usr/sbin/qm rollback "{{ item }}" preupgrade
  loop:
    - 102
    - 106
    - 107
    - 108
    - 110
    - 111
    - 112
    - 113
  tags:
   - rollback

- name: Shutdown Nodes
  command: /usr/sbin/qm shutdown "{{ item }}"
  loop:
    - 102
    - 106
    - 107
    - 108
    - 110
    - 111
    - 112
    - 113
  tags:
   - shutdown


- name: Find Nodes Across Cluster
  command: pvesh get /cluster/resources --type vm
  register: vm_node_list
  tags: findnode






#    - name: Take Snapshot
#       command: /usr/sbin/qm snapshot "{{ item }}" preupgrade
#       loop:
#        - 102
#        - 106
#        - 107
#        - 108
#        - 110
#        - 111
#        - 112
#        - 113
#       tags:
#        - snapshot

