---
- name: Start Nodes
  command: /usr/sbin/qm start "{{ item }}"
  loop:
    - "{{ rhel6_01 }}"  
    - "{{ rhel6_02 }}"
    - "{{ rhel7_01 }}"
    - "{{ rhel7_02 }}"
    - "{{ rhel8_01 }}"
    - "{{ rhel8_02 }}"
    - "{{ rhel9_01 }}"
    - "{{ rhel9_02 }}"
  tags:
    - start

- name: Stop Nodes
  command: /usr/sbin/qm stop "{{ item }}"
  loop:
    - "{{ rhel6_01 }}"  
    - "{{ rhel6_02 }}"
    - "{{ rhel7_01 }}"
    - "{{ rhel7_02 }}"
    - "{{ rhel8_01 }}"
    - "{{ rhel8_02 }}"
    - "{{ rhel9_01 }}"
    - "{{ rhel9_02 }}"
  tags:
   - stop

- name: Reset Nodes to Base Snapshot
  command: /usr/sbin/qm rollback "{{ item }}" preupgrade
  loop:
    - "{{ rhel6_01 }}"  
    - "{{ rhel6_02 }}"
    - "{{ rhel7_01 }}"
    - "{{ rhel7_02 }}"
    - "{{ rhel8_01 }}"
    - "{{ rhel8_02 }}"
    - "{{ rhel9_01 }}"
    - "{{ rhel9_02 }}"
  tags:
   - rollback

- name: Shutdown Nodes
  command: /usr/sbin/qm shutdown "{{ item }}"
  loop:
    - "{{ rhel6_01 }}"  
    - "{{ rhel6_02 }}"
    - "{{ rhel7_01 }}"
    - "{{ rhel7_02 }}"
    - "{{ rhel8_01 }}"
    - "{{ rhel8_02 }}"
    - "{{ rhel9_01 }}"
    - "{{ rhel9_02 }}"
  tags:
   - shutdown


- name: Find Nodes Across Cluster
  command: pvesh get /cluster/resources --type vm
  register: vm_node_list
  tags: findnode

