---
- setup:
    gather_subset: min
    filter:
      - ansible_distribution(
      - ansible_hostname
  tags: always

- name: Register to Satellite
  command: "subscription-manager register --org={{ org }} --activationkey={{ reg_key6 }}"
  tags: [ never, register ]

- name: Unregister to Satellite
  command: "subscription-manager unregister"
  tags: [ never, unregister ]

