---
- hosts: all
  gather_facts: no
  tasks:
    - name: Start Lab VMs
      ansible.builtin.include_role:
        name: roles/lab_hypervisor_tasks
        tasks_from: main
      tags: start

    - name: Stop Lab VMs
      ansible.builtin.include_role:
        name: roles/lab_hypervisor_tasks
        tasks_from: main
      tags: stop

    - name: Rollback Lab VMs
      ansible.builtin.include_role:
        name: roles/lab_hypervisor_tasks
        tasks_from: main
      tags: rollback

    - name: Find Lab VMs Across Cluster
      ansible.builtin.include_role:
        name: roles/lab_hypervisor_tasks
      tags: findnode

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: findnode
        verbosity: 2












#     - name: Reset VMs to Snapshot
#       include_role:
#         name: lab_hypervisory_tasks
#         tasks_from: Reset Nodes to Snapshot

