---
- hosts: all
  gather_facts: false
  ignore_unreachable: true
  become: true
  tasks:
      - setup:
          gather_subset: min
          filter:
            - ansible_distribution*
            - ansible_hostname

      - name: Check Reboot flag
        shell: "grep -E 'TRUE|FALSE' /opt/Tanium/TaniumClient/Tools/CustomTags.txt"
        register: autoreboot
        failed_when: false
        ignore_errors: true
        async: 60
        poll: 5

      - name: Missing Reboot flag
        when: autoreboot.rc == 2
        debug: msg="{{ ansible_hostname }} is missing the CustomTags.txt file. Open incident with the Patch Engineering Team"
        ignore_errors: true

      - name: Check for any generic yum errors
        shell: yum update --assumeno
        register: yum_generic_error
        failed_when: false
        ignore_errors: true
        async: 60
        poll: 5

      - name: Generic yum errors found
        when: yum_generic_error.stdout is search("Error")
        debug: msg="There is a yum error that will prevent the update. Open incident with Server Linux Operations"
        ignore_errors: true
        async: 60
        poll: 5

      - name: Find yumtx files in /tmp
        find:
          paths: /tmp/
          patterns: '*.yumtx'
          age: 1m
          recurse: false
        register: yumtx

      - name: Delete yum transaction files from /tmp
        file:
          path: "{{ item.path }}"
          state: absent
        with_items: "{{ yumtx.files }}"

      - name: Find user created yum cache in /var/tmp
        find:
          paths: /var/tmp/
          file_type: directory
          patterns: 'yum-*'
          age: 1m
          recurse: false
        register: useryum

      - name: Delete user created yum cache in /var/tmp
        file:
          path: "{{ item.path }}"
          state: absent
        with_items: "{{ useryum.files }}"
        ignore_errors: true

      - name: Check RHSM Base URL
        shell: grep -i subscription.rhsm.redhat.com /etc/rhsm/rhsm.conf
        register: rhsm_base_url
        ignore_errors: true

      - name: Wrong RHSM Base URL
        when: rhsm_base_url.rc == 1
        failed_when: rhsm_base_url.rc == 1
        debug: msg="Wrong satellite server configured for this host. Open INC with Server Linux Operations"
        ignore_errors: true

      - name: Check if repos are enabled
        shell: subscription-manager repos --list-enabled
        register: repos_enabled
        async: 60
        poll: 5
        ignore_errors: true

      - name: No repos enabled
        when: repos_enabled.stdout is search("There were no available repositories matching the specified criteria.")
        failed_when: repos_enabled.stdout is search("There were no available repositories matching the specified criteria.") or repos_enabled.stdout is search("This system has no repositories available through subscriptions.")
        debug: msg="No repos enabled. Open INC with Linux Operations"
        ignore_errors: true

      - name: See if rpm is working
        args:
          warn: false
        command:
          cmd: rpm -qa redhat-release*
        become: true
        register: rpm_check
        failed_when: rpm_check.stderr is search("Berkeley") or repos_enabled.changed == False or repos_enabled.stderr is search("PANIC") or rpm_check.stderr is search("Cannot allocate memory")
        changed_when: false
        ignore_errors: true
        poll: 5
        async: 60

      - name: See if repos times out
        command:
          cmd: subscription-manager repos --list-enabled
        become: true
        register: subscription_manager_repos
        failed_when: subscription_manager_repos.stderr is search("Berkeley")
        changed_when: false
        ignore_errors: true
        poll: 5
        async: 60

      - name: Rebuild rpmdb if broken
        block:
          - name: Stop TaniumClient (RHEL 6)
            service:
              name: TaniumClient
              state: stopped
            when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")

          - name: Stop taniumclient (RHEL 7 or 8)
            service:
              name: taniumclient
              state: stopped
            when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7") or
                  (ansible_distribution == "RedHat" and ansible_distribution_major_version == "8") or
                  (ansible_distribution == "RedHat" and ansible_distribution_major_version == "9")

          - name: Stop rhsmcertd
            service:
              name: rhsmcertd
              state: stopped

          - name: Attempt to find what is using subscription-manager
            shell:
              cmd: grep "[[:digit:]]*" /var/run/rhsm/cert.pid
            become: true
            register: sub_man_pid
            ignore_errors: true
            changed_when: false

          - name: Attempt to kill what is using
            block:
              - name: Kill what is using subscription-manager
                shell:
                  cmd: kill -9 $(cat /var/run/rhsm/cert.pid)
                register: kill_certpid
                become: true

              - name: Remove /var/run/rhsm/cert.pid if process doesn't exist
                shell:
                  cmd: rm /var/run/rhsm/cert.pid
                become: true
                when: 'kill_certpid.failed == true and kill_certpid.stderr is search("No such process")'
            when: sub_man_pid.failed == false
            ignore_errors: true

          - name: Rebuild tasks
            block:
              - name: Kill all rpm/yum commands
                shell:
                  cmd: kill -9 $(ps -ef | grep -v grep | grep "rpm\|yum" | awk '{ if($3=1){ print $2 } }')
                ignore_errors: true

              - name: Remove /var/lib/rpm/.dbenv.lock
                file:
                  path: /var/lib/rpm/.dbenv.lock
                  state: absent
                become: true

              - name: Remove /var/lib/rpm/.rpm.lock
                file:
                  path: /var/lib/rpm/.rpm.lock
                  state: absent
                become: true

              - name: Back rpmdb files
                shell:
                  cmd: mv /var/lib/rpm/__db* /tmp/.

              - name: Rebuild db
                command:
                  cmd: rpm --rebuilddb
                poll: 5
                async: 120

              - name: Start rhsmcertd
                service:
                  name: rhsmcertd
                  state: started

              - name: See if rpm is working again
                command:
                  cmd: rpm -qa redhat-release*
                when: rpm_check.failed == true
                changed_when: false
                poll: 5
                async: 60

              - name: See if repos works
                command:
                  cmd: subscription-manager repos
                become: true
                register: subscription_manager_repos_retry
                when: subscription_manager_repos.failed == true
                failed_when: subscription_manager_repos_retry.stderr is search("Berkeley")
                changed_when: false
                poll: 5
                async: 60
            rescue:
              - name: Put rpmdb files back
                shell:
                  cmd: mv /tmp/__db* /var/lib/rpm/
                register: rpmdb_revert

              - name: Successfully put back db files
                fail:
                  msg: "Failed to recover db, reverted successfully"
                when: rpmdb_revert.failed == false
        always:
          - name: Start TaniumClient (RHEL 6)
            service:
              name: TaniumClient
              state: started
            when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")

          - name: Start taniumclient (RHEL 7)
            service:
              name: taniumclient
              state: started
            when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7") or
                  (ansible_distribution == "RedHat" and ansible_distribution_major_version == "8") or
                  (ansible_distribution == "RedHat" and ansible_distribution_major_version == "9")

          - name: Start rhsmcertd
            service:
              name: rhsmcertd
              state: started
        when: rpm_check.failed == true or subscription_manager_repos.failed == true
        become: true

      - name: Clean yum cache
        command: yum clean all
        async: 120
        poll: 10
        args:
          warn: false
        register: clean_chk
        ignore_errors: true
