---
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - setup:
        gather_subset: min
        gather_timeout: 60
        filter:
          - ansible_distribution*
          - ansible_hostname
          - date_time

    - name: Check Last Update RHEL6/7
      shell: yum history list all | grep "E, I, U" | grep -i "root" | head -n 1 | awk '{ print $6 }'
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version <= "7")
      register: last_update7

    - name: Check Last Reboot RHEL6/7
      shell: "last reboot | awk '{ print $6, $7, $8 }' | head -n 1"
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version <= "7")
      register: last_reboot7

    - name: Check Last Update RHEL8
      shell: yum history | grep "E, I, U" | head -n 1 | awk '{ print $4 }'
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version >= "8")
      register: last_reboot8

    - name: Check Last Reboot RHEL8
      shell: "last reboot | awk '{ print $6, $7, $8 }' | head -n 1"
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version >= "8")
      register: last_reboot8

    - name: Print Last Update and Reboot RHEL6/7
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version <= "7")
      debug:
        msg: "{{ ansible_hostname }} last updated on {{ last_update7.stdout }}, last rebooted on {{ last_reboot7.stdout }}"

    - name: Print Last Update and Reboot on RHEL8
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version >= "8")
      debug:
        msg: "{{ ansible_hostname }} last updated on {{ last_update8.stdout }}, last rebooted on {{ last_reboot8.stdout }}"

