---
- name: Reboot Server
  hosts: all,!exclude
  gather_facts: no
  become: true

  tasks:
    - name: Reboot Server (Wait for 20 min)
      reboot:
        msg: "Reboot initiated by Ansible authorized by {{ change_id }}"
        reboot_timeout: 1200

