---
- hosts: all,!lab_host_hypervisor,!rhel6
  gather_facts: false
  become: true
  pre_tasks:
    - name: Stop ServiceOne
      systemd:
        state: stopped
        name: serviceone
      tags: [ never, serviceone ]

  roles:
    - roles/linux_patching 

  post_tasks:
    - name: Start ServiceOne
      systemd:
        state: started
        name: serviceone
      tags: [ never, serviceone ]
